@startuml

left to right direction

actor :User 1: as p1
actor :User 2: as p2
actor :User 3: as p3
actor :User 4: as p4
actor :User 5: as p5
actor :User 6: as p6
actor :User 7: as p7
actor :User 8: as p8
actor :User 9: as p9
actor :User 10: as p10
usecase (Enter Username) as UC1
usecase (Enter Password) as UC2
usecase (Send Message to Chat With Other Users) as UC3
usecase (Log Out of Chatroom) as UC4
usecase (Clear Chat Window) as UC5
usecase (Login to Chatroom) as UC6
usecase (View Whether Connected to the Server) as UC7

p1 --> UC1
p2 --> UC1
p3 --> UC1
p4 --> UC1
p5 --> UC1
p6 --> UC1
p7 --> UC1
p8 --> UC1
p9 --> UC1
p10 --> UC1

p1 --> UC2
p2 --> UC2
p3 --> UC2
p4 --> UC2
p5 --> UC2
p6 --> UC2
p7 --> UC2
p8 --> UC2
p9 --> UC2
p10 --> UC2

p1 --> UC3
p2 --> UC3
p3 --> UC3
p4 --> UC3
p5 --> UC3
p6 --> UC3
p7 --> UC3
p8 --> UC3
p9 --> UC3
p10 --> UC3

p1 --> UC4
p2 --> UC4
p3 --> UC4
p4 --> UC4
p5 --> UC4
p6 --> UC4
p7 --> UC4
p8 --> UC4
p9 --> UC4
p10 --> UC4

p1 --> UC5
p2 --> UC5
p3 --> UC5
p4 --> UC5
p5 --> UC5
p6 --> UC5
p7 --> UC5
p8 --> UC5
p9 --> UC5
p10 --> UC5

p1 --> UC6
p2 --> UC6
p3 --> UC6
p4 --> UC6
p5 --> UC6
p6 --> UC6
p7 --> UC6
p8 --> UC6
p9 --> UC6
p10 --> UC6

p1 --> UC7
p2 --> UC7
p3 --> UC7
p4 --> UC7
p5 --> UC7
p6 --> UC7
p7 --> UC7
p8 --> UC7
p9 --> UC7
p10 --> UC7

@enduml